---
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
  children:
    vps:
      hosts:
        nerd2:
          ansible_host: "{{ lookup('env', 'NERD2_TS_IP') | default(lookup('env', 'NERD2_IP'), true) }}"
    proxmox:
      hosts:
        pve2:
          ansible_host: "nas.home.arpa"
          proxmox_node_name: "nas" # May differ from inventory hostname

    # Dynamic groups, autopopulated during playbook execution
    # Empty placeholders suppress ansible-lint warnings
    swarm: {}
    lxc: {}
    vm: {}
