#:schema https://mise.jdx.dev/schema/mise-task.json

["site:deploy"]
description = " " # "Create and provision all hosts"
run = [
  "mise run tf:apply",
  "mise run lxc:deploy",
  "mise run vm:deploy",
  "mise run vps:deploy",
  "mise run swarm:deploy"
  ]

# ================================================================================

["lxc:deploy"]
description = " " # "Deploy LXC containers"
run = "ansible-playbook ansible/playbooks/lxc.yml"

["lxc:check"]
description = " " # "Dry-run LXC provisioning"
run = "ansible-playbook ansible/playbooks/lxc.yml --check --diff"

# ================================================================================

["vm:deploy"]
description = " " # "Deploy VMs"
run = "ansible-playbook ansible/playbooks/vm.yml"

["vm:check"]
description = " " # "Dry-run VM provisioning"
run = "ansible-playbook ansible/playbooks/vm.yml --check --diff"

# ================================================================================

["vps:deploy"]
description = " " # "Deploy VPS hosts"
run = "ansible-playbook ansible/playbooks/vps.yml"

["vps:check"]
description = " " # "Dry-run VPS deployment"
run = "ansible-playbook ansible/playbooks/vps.yml --check --diff"

["vps:first-run"]
description = " " # "First-time deployment with password authentication"
run = "ansible-playbook ansible/playbooks/vps.yml --ask-pass --user root --extra-vars \"ansible_host={{ env.VPS_PUBLIC_IP }}\""
