#:schema https://mise.jdx.dev/schema/mise-task.json
#:tombi schema.strict = false

["vm:deploy"]
description = " " # "Deploy VM to specific host(s)"
depends = ["tf:apply"]
usage = '''
arg "[hosts]" help="Hostnames (e.g. vmtest1,vmtest2)"
arg "[tags]" help="Ansible tags (e.g. common,ssh,docker)"
'''
env = { DEPLOY_GROUP = "vm" }
file = ".mise/scripts/deploy.sh"

["vm:check"]
description = " " # "Dry run VM provisioning (check mode)"
env = { DEPLOY_GROUP = "vm", DEPLOY_INTERACTIVE = "false", DEPLOY_CHECK_MODE = "true" }
file = ".mise/scripts/deploy.sh"
