---
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
  children:
    vps:
      hosts:
        swarm-vps:
          ansible_host: "{{ lookup('env', 'VPS_ADDR') }}"
    lxc:
      hosts:
        swarm-lxc:
          ansible_host: swarm-lxc
        fileserver:
          ansible_host: fileserver
        mediaserver:
          ansible_host: mediaserver
    vm:
      hosts:
        swarm-vm:
          ansible_host: swarm-vm

    # Dynamic group — populated by discover_swarm.yml
    swarm: {}
