---
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
  children:
    vps:
      hosts:
        swarm-vps:
          ansible_host: "{{ lookup('env', 'VPS_ADDR') }}"
    proxmox:
      hosts:
        pve:
          ansible_host: "{{ lookup('env', 'PVE_HOST_ADDR') }}"
          proxmox_node_name: "{{ lookup('env', 'PVE_NODE_NAME') }}"
      children:
        lxc: {}
        vm: {}

    # Dynamic groups — populated during playbook execution
    swarm: {}
