---
# yaml-language-server: $schema=../schemas/host.schema.json

# Users
users_list:
  - name: swarm
    group: swarm
    uid: 1000
    gid: 1000
    shell: /usr/sbin/nologin
    home: /nonexistent
    create_home: false

# Packages
packages_install_shell: true
packages_install_network: true

# Dotfiles
dotfiles_enabled: true
dotfiles_deploy_args: "bash claude nano"

# Tailscale
tailscale_enabled: true
tailscale_tags: ["ansible", "swarm"]
tailscale_ip: "100.88.0.3"
tailscale_bind_ssh: false

# Docker
docker_enabled: true
docker_data_root: "/data/docker-data"
docker_containerd_root: "/data/containerd"
docker_mtu: 1280
docker_dns_servers: []
docker_dns_search: []
docker_gpu_enabled: true
docker_swarm_enabled: true
docker_swarm_init: false
docker_swarm_role: worker
docker_swarm_advertise_addr: "{{ tailscale_ip }}"
docker_swarm_listen_addr: "{{ tailscale_ip }}:2377"
docker_swarm_data_path_port: 4789
docker_swarm_labels: { type: "lxc", location: "onprem", ip: "private", gpu: "true", storage: "true" }
docker_swarm_availability: active
docker_insecure_registries:
  - "registry.{{ lookup('env', 'DOMAIN_PRIVATE') }}"
