---
# yaml-language-server: $schema=../schemas/host.schema.json

net_dns_configure: true
net_ntp_configure: true

# Hostname
hostname_configure: true
hostname: "{{ ansible_host }}"

# Packages
packages_install_shell: true
packages_install_network: true
packages_extra_list:
  - "cifs-utils"

# Dotfiles
dotfiles_enabled: true
dotfiles_deploy_args: "bash claude nano"

# Users
users_list:
  - name: swarm
    group: swarm
    uid: 1000
    gid: 1000
    shell: /usr/sbin/nologin
    home: /nonexistent
    create_home: false

# Tailscale
tailscale_enabled: true
tailscale_tags: ["ansible", "swarm"]
tailscale_ip: "100.88.0.1"
tailscale_bind_ssh: true

# Docker
docker_enabled: true
docker_mtu: 1280
docker_dns_servers: []
docker_dns_search: []
docker_swarm_enabled: true
docker_swarm_init: false
docker_swarm_role: worker
# docker_data_root: "/data/docker-data"
docker_swarm_advertise_addr: "{{ tailscale_ip }}"
docker_swarm_listen_addr: "{{ tailscale_ip }}:2377"
docker_swarm_data_path_port: 4789
docker_swarm_vxlan_interface: tailscale0
docker_swarm_labels: { type: "vps", location: "cloud", ip: "public" }
docker_swarm_availability: active
docker_insecure_registries:
  - "registry.{{ lookup('env', 'DOMAIN_PRIVATE') }}"
