---
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
  children:
    vps:
      hosts:
        nerd1:
          ansible_host: "{{ lookup('env', 'NERD1_TS_IP') | default(lookup('env', 'NERD1_IP'), true) }}"
    proxmox:
      hosts:
        pve1:
          ansible_host: "proxmox.home.arpa"
          proxmox_node_name: "proxmox" # May differ from inventory hostname

    # Dynamic groups, autopopulated during playbook execution
    # Empty placeholders suppress ansible-lint warnings
    swarm: {}
    lxc: {}
    vm: {}
