---
# yaml-language-server: $schema=https://json.schemastore.org/yamllint.json

extends: default

ignore: |
  vault.yml
  .ansible/
  .venv/
  .old/
  .tmp/

rules:
  line-length:
    max: 160
    level: warning
  truthy:
    check-keys: false
    allowed-values: ["true", "false", "yes", "no"]
  comments:
    min-spaces-from-content: 1
    require-starting-space: false
  # Required by ansible-lint
  comments-indentation: false
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
  braces:
    max-spaces-inside: 1
  brackets:
    max-spaces-inside: 1
  indentation:
    spaces: 2
    indent-sequences: consistent
  document-start:
    present: true
  empty-lines:
    max: 2
    max-start: 0
    max-end: 1
