TS_TAILNET: ENC[AES256_GCM,data:5YjyRC5DtKrGwiUYOZa/kqE=,iv:bBLq+RtxJ+Gl1esBM5RrQ084wkK8LE4+oM0I4F3rkzo=,tag:2G6/bJq1KWpCm0L1Kb/3kw==,type:str]
TS_OAUTH_KEY: ENC[AES256_GCM,data:peJSiy3D2kzcpU/WqF1caPBByKy2wTMDPWHY6uqbcgJiItKDywk2/WGsKoAi6iI24Dnh/T8vfOWcYqhiDJt1tA==,iv:/ToeHDSd6U8uvppovZOaW0aQM+R0RRF5Ke3BLA2lITc=,tag:4j+ZDlEsdQfkffPWprr4mg==,type:str]
PROXMOX_TOKEN_SECRET: ENC[AES256_GCM,data:4K4S3qUCQE/vVq0MBG+5dc/ggJjVGx+yrqTeybWkLRsO+cN1,iv:kdlFp49DL1jlFzw7BVLJUPT0pZBzhJNIjthZJ+HRUZw=,tag:czksVNHewpkfe4eL02Qscg==,type:str]
VPS_PUBLIC_IP: ENC[AES256_GCM,data:u1B9E5tfb0t4NHwfbNBQ,iv:qqB9Tremw63fsB8SCAm7Wsk2+ltT/miq9LJi6Ar0d2U=,tag:e7YxegPSPE3AkI+ZJJZNfQ==,type:str]
DOMAIN_PUBLIC: ENC[AES256_GCM,data:xOgqSAEjThJFgw==,iv:ZXJX7u75Yp2wIgpNCde9E2B5dk1U+n7cbnlioiV4l9g=,tag:asuHAcar9Xn5BFyISQjTQg==,type:str]
DOMAIN_PRIVATE: ENC[AES256_GCM,data:7FIO9+1f2QkzLfjX,iv:yAfD3WTjEJV/HbDQXzp5imsHayDJ2GsDvamqbuh9sKs=,tag:Xey7qb/x0D5UVnnN5ssL3g==,type:str]
sops:
    age:
        - recipient: age1m2a7jfn9p999pw5l3w3x2556j42lx4ulr3d2n00ly5rn5a968ctssh0a7k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsQUZPbHZDYkdnVFdoWHpj
            MjA5RXJicXV0bHViblZQa0YrSkN0QkRPWHcwCjNhelZUWFp3TE8wRm5MQk0xRkVh
            WmN6QVIzVzBweWF3OW50RiszSUNMTHcKLS0tIDg1Q2dUQ3dxZ2pteHJnN3JINFBi
            UksxbEY5bDhNUElXaGZVa0ZwNFFDblkKxMkM+UB1FurYmULNHk3U8eGutTr8CyxD
            sFBMmhdI0k9vyITXcLD+vMClD1vViOXgQI9xCA5buxxv+p4SPtOAzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-15T21:09:25Z"
    mac: ENC[AES256_GCM,data:psiSON9KdoGLixHpZSjT6sFToH4E2qNe/I2Jo+eFN3rBpHQKgIIw5y8kSf5GD82ARwl1XfOMpkMLZbwD35Kc63xZPITPrMG0M0c5AP4SteN2PgQ5TXIEFZzB7Askz3bl5XDnRCfQMFcHjZDOtMSMoJ5T6yW8e3lmQB/vXnyGaTg=,iv:JSO31dpqRB9kClFd4mYPtjqH+xtIZA8I0GaM33/lbGs=,tag:WiiaLG27mH7J50eJoR+ekw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
