TS_TAILNET: ENC[AES256_GCM,data:5YjyRC5DtKrGwiUYOZa/kqE=,iv:bBLq+RtxJ+Gl1esBM5RrQ084wkK8LE4+oM0I4F3rkzo=,tag:2G6/bJq1KWpCm0L1Kb/3kw==,type:str]
TS_OAUTH_KEY: ENC[AES256_GCM,data:peJSiy3D2kzcpU/WqF1caPBByKy2wTMDPWHY6uqbcgJiItKDywk2/WGsKoAi6iI24Dnh/T8vfOWcYqhiDJt1tA==,iv:/ToeHDSd6U8uvppovZOaW0aQM+R0RRF5Ke3BLA2lITc=,tag:4j+ZDlEsdQfkffPWprr4mg==,type:str]
PROXMOX_TOKEN_SECRET: ENC[AES256_GCM,data:4K4S3qUCQE/vVq0MBG+5dc/ggJjVGx+yrqTeybWkLRsO+cN1,iv:kdlFp49DL1jlFzw7BVLJUPT0pZBzhJNIjthZJ+HRUZw=,tag:czksVNHewpkfe4eL02Qscg==,type:str]
NERD2_PUBLIC_IP: ENC[AES256_GCM,data:QOCwWvTG8VU5WqY6TI7E,iv:A23ncOeE5O+hyyksK8KgHQplwtJKRi5KPUQC+gX/Z7Q=,tag:oWkZzE6W6DnK76QrZCM4zg==,type:str]
DOMAIN_PUBLIC: ENC[AES256_GCM,data:xOgqSAEjThJFgw==,iv:ZXJX7u75Yp2wIgpNCde9E2B5dk1U+n7cbnlioiV4l9g=,tag:asuHAcar9Xn5BFyISQjTQg==,type:str]
DOMAIN_PRIVATE: ENC[AES256_GCM,data:7FIO9+1f2QkzLfjX,iv:yAfD3WTjEJV/HbDQXzp5imsHayDJ2GsDvamqbuh9sKs=,tag:Xey7qb/x0D5UVnnN5ssL3g==,type:str]
sops:
    age:
        - recipient: age1m2a7jfn9p999pw5l3w3x2556j42lx4ulr3d2n00ly5rn5a968ctssh0a7k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsQUZPbHZDYkdnVFdoWHpj
            MjA5RXJicXV0bHViblZQa0YrSkN0QkRPWHcwCjNhelZUWFp3TE8wRm5MQk0xRkVh
            WmN6QVIzVzBweWF3OW50RiszSUNMTHcKLS0tIDg1Q2dUQ3dxZ2pteHJnN3JINFBi
            UksxbEY5bDhNUElXaGZVa0ZwNFFDblkKxMkM+UB1FurYmULNHk3U8eGutTr8CyxD
            sFBMmhdI0k9vyITXcLD+vMClD1vViOXgQI9xCA5buxxv+p4SPtOAzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T17:06:17Z"
    mac: ENC[AES256_GCM,data:eVJ8R1AbKwedBiklXeE/N7tn/L+sdCQQ94fceKGx4atEw5NxWONassCmIkgc24DunYUKnYV9fDaoAIBqksG/IRSnHkqCTMbWJLQSzb5qjKBZLG89XNjoUSJC2ThzSrlHLNJRtCJiTDY4Ln2mfx75q1kUU+BgvHaumn1nhbqJ29o=,iv:vt0NXGP9FEiJq9EMmpn5SgXpG/AsXbCs5trcw/e3Qzw=,tag:f3zE+ptHJ0kVWXe391ZfiQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
