[env]
_.file = { path = "{{config_root}}/.secrets/prod.sops.yaml", redact = true }

# Proxmox
PVE_HOST_ADDR = "nas.home.arpa"
PVE_NODE_NAME = "nas"

# VPS
VPS_ADDR = "100.88.0.2"
VPS_HOSTNAME = "prod-swarm-vps"
VPS_PUBLIC_IP = "{{ env.NERD2_PUBLIC_IP }}"
