[env]
_.file = { path = "{{config_root}}/.secrets/prod.sops.yaml", redact = true }

# Proxmox
PVE_HOST_ADDR = "nas.home.arpa"
PVE_NODE_NAME = "nas"

# VPS
VPS_ADDR = "100.88.0.2"
VPS_HOSTNAME = "prod-swarm-vps"
VPS_PUBLIC_IP = "{{ env.NERD2_PUBLIC_IP }}"

# Terraform
TF_VAR_pve_download_storage = "zfs-cold"
TF_VAR_pve_node_name = "{{ env.PVE_NODE_NAME }}"
TF_VAR_pve_host_addr = "{{ env.PVE_HOST_ADDR }}"
PROXMOX_VE_ENDPOINT = "https://{{ env.PVE_HOST_ADDR }}:8006/"
