[env]
_.file = { path = "{{config_root}}/.secrets/dev.sops.yaml", redact = true }

# Proxmox
PVE_HOST_ADDR = "proxmox.home.arpa"
PVE_NODE_NAME = "proxmox"

# VPS
VPS_ADDR = "100.88.0.1"
VPS_HOSTNAME = "nerd1"
VPS_PUBLIC_IP = "{{ env.NERD1_PUBLIC_IP }}"
