---
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
  children:
    vps:
      hosts:
        swarm-vps:
          ansible_host: "{{ lookup('env', 'VPS_ADDR') }}"
    lxc:
      hosts:
        swarm-lxc:
        fileserver:
        mediaserver:
    vm:
      hosts:
        swarm-vm:
    swarm: {} # Dynamic group populated by discover_swarm.yml
