---
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
  children:
    vps:
      hosts:
        swarm-vps:
          env_scope: prod
          ansible_host: "swarm-vps"
        swarm-vps-dev:
          env_scope: dev
          ansible_host: "swarm-vps-dev"
    lxc:
      hosts:
        docker-lxc:
          env_scope: prod
        swarm-lxc:
          env_scope: prod
        swarm-lxc-dev:
          env_scope: dev
        fileserver:
          env_scope: prod
        fileserver-dev:
          env_scope: dev
    vm:
      hosts:
        swarm-vm:
          env_scope: prod
        swarm-vm-dev:
          env_scope: dev
    swarm: {} # Dynamic group populated by discover_swarm.yml
